-- local config = {
--   lazy = false,
--   connections = {
--     {
--       name = "test_db",
--       type = "sqlite",
--       url = "home/mason/.config/lvim/test_db",
--     },
--   },
-- }
-- 
-- require("dbee").setup(config)
